#!/usr/bin/bash

# ctscripts makes a directory containing codetext scripts

pw0="$(dirname "$0")"

# make directory for codetext scripts
mkdir ct
cp "$pw0/tangle.py" "$pw0/cttoorg"* "$pw0/orgtoct"* "$pw0/cttonw" "$pw0/orgtonw.py" "$pw0/ct" ct
# make the scripts executable
chmod u+x ct/*
